const data = {
  products: [
    {
      _id: '1',
      name: 'ELON MUSK',
      slug: 'elon-musk',
      category: 'books',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'none',
      rating: 4.5,
      numReviews: 10,
      description: 'Biography of Elon Musk',
    },
    {
      _id: '2',
      name: 'DEEP WORK.',
      slug: 'deep-work',
      category: 'books',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'none',
      rating: 4.0,
      numReviews: 10,
      description: 'Insights about work.',
    },
    {
      _id: '3',
      name: 'RICH DAD POOR DAD',
      slug: 'rich-dad-poor-dad',
      category: 'books',
      image: '/images/p3.jpg',
      price: 65,
      countInStock: 5,
      brand: 'none',
      rating: 4.5,
      numReviews: 10,
      description: 'Real life emotions.',
    },
    {
      _id: '4',
      name: 'The Philosophy of money',
      slug: 'the-philosophy-of-money',
      category: 'books',
      image: '/images/p4.jpg',
      price: 25,
      countInStock: 15,
      brand: 'none',
      rating: 4.5,
      numReviews: 14,
      description: 'Valley of money',
    },
  ],
};
export default data;
